version: '3.9'

services:  
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: devsdb
    ports:
      - "5433:5432"
    volumes:
      - ./data:/data/postgres
  api:
      container_name: apidevs
      build: .
      command: yarn dev
      env_file: .env
      ports:
        - "3333:3333"
      volumes:
        - .:/usr/src/app
      depends_on:
        - db     