version: '3.9'

services:  
  db:
    container_name: db
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - ./data:/data/postgres
  api:
      container_name: apidevs
      build: .
      command: >
        sh -c "yarn && yarn docker:migration:run && yarn dev"
      env_file: .env
      ports:
        - "3333:3333"
      volumes:
        - .:/usr/src/app
      depends_on:
        - db     